admin/config/routes.rb
Rails.application.routes.draw do
  resources :hosts
  root :to => "login#index"
  get 'login/index'
  post 'login/login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

admin/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

admin/app/models/host.rb
class Host < ApplicationRecord
end

admin/app/models/user.rb
class User < ApplicationRecord
end

admin/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

admin/app/controllers/host_controller.rb
class HostController < ApplicationController
  def index
  end
end

admin/app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: [:show, :edit, :update, :destroy]

  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
  end

  # GET /hosts/new
  def new
    @host = Host.new
  end

  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(host_params)

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, notice: 'Host was successfully created.' }
        format.json { render :show, status: :created, location: @host }
      else
        format.html { render :new }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1
  # PATCH/PUT /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to @host, notice: 'Host was successfully updated.' }
        format.json { render :show, status: :ok, location: @host }
      else
        format.html { render :edit }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host.destroy
    respond_to do |format|
      format.html { redirect_to hosts_url, notice: 'Host was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def host_params
      params.require(:host).permit(:ip_listen, :ip_serv, :port, :port_passive_begin, :port_passive_end)
    end
end

admin/app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end

  def login
    puts params
    @user = User.find_by(:name => params[:name])
    if @user == nil
      puts "hello"
      flash.now[:error] = "用户不存在"
      render 'index'
    elsif @user.password != params[:password]
      puts "world"
      flash.now[:error] = "密码错误"
      render 'index'
    else
      session[:user] = @user
      redirect_to hosts_path
    end
  end

end

admin/app/helpers/application_helper.rb
module ApplicationHelper
end

admin/app/helpers/host_helper.rb
module HostHelper
end

admin/app/helpers/hosts_helper.rb
module HostsHelper
end

admin/app/helpers/login_helper.rb
module LoginHelper
end

admin/app/views/host/index.html.erb
<h1>Host#index</h1>
<p>Find me in app/views/host/index.html.erb</p>

admin/app/views/hosts/_form.html.erb
<%= form_with(model: host, local: true) do |form| %>
  <% if host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
      <% host.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ip_listen %>
    <%= form.text_field :ip_listen, id: :host_ip_listen %>
  </div>

  <div class="field">
    <%= form.label :ip_serv %>
    <%= form.text_field :ip_serv, id: :host_ip_serv %>
  </div>

  <div class="field">
    <%= form.label :port %>
    <%= form.number_field :port, id: :host_port %>
  </div>

  <div class="field">
    <%= form.label :port_passive_begin %>
    <%= form.number_field :port_passive_begin, id: :host_port_passive_begin %>
  </div>

  <div class="field">
    <%= form.label :port_passive_end %>
    <%= form.number_field :port_passive_end, id: :host_port_passive_end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

admin/app/views/hosts/edit.html.erb
<h1>Editing Host</h1>

<%= render 'form', host: @host ,:class => "form-inline" %>


<%= link_to 'Show', @host %> |
<%= link_to 'Back', hosts_path %>

admin/app/views/hosts/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Ftp服务主机器列表</h4>

<%= link_to '增加服务器', new_host_path ,:class => 'btn btn-info btn-xs active'%>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>监听IP</th>
      <th>服务IP</th>
      <th>服务端口</th>
      <th>被动端口开始</th>
      <th>被动端口结束</th>
      <th colspan="3">操作</th>
    </tr>
  </thead>

  <tbody>
    <% @hosts.each do |host| %>
      <tr>
        <td><%= host.ip_listen %></td>
        <td><%= host.ip_serv %></td>
        <td><%= host.port %></td>
        <td><%= host.port_passive_begin %></td>
        <td><%= host.port_passive_end %></td>
        <td><%= link_to '查看', host ,:class => 'btn btn-info btn-xs active'%></td>
        <td><%= link_to '编辑', edit_host_path(host) ,:class => 'btn btn-primary btn-xs active'%></td>
        <td><%= link_to '删除', host, method: :delete, data: { confirm: '确定要删除?' },:class => 'btn btn-danger btn-xs active' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

admin/app/views/hosts/new.html.erb
<h1>New Host</h1>

<%= render 'form', host: @host %>

<%= link_to 'Back', hosts_path %>

admin/app/views/hosts/show.html.erb
<p class="form-group" id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_host_path(@host),:class => 'btn btn-info btn-xs active' %> |
<%= link_to 'Back', hosts_path ,:class => 'btn btn-info btn-xs active'%>

<div class="form-horizontal">

  <p class="form-group">
    <label class="col-sm-2 control-label">Ip listen:</label>
  <span class="col-sm-10" > <%= @host.ip_listen %> </span>
  </p>

  <p class="form-group">
    <label class="col-sm-2 control-label">Ip serv:</label>
    <span class="col-sm-10" > <%= @host.ip_serv %> </span>
  </p>

  <p class="form-group">
    <label class="col-sm-2 control-label">Port:</label>
    <span class="col-sm-10" > <%= @host.port %> </span>
  </p>

  <p class="form-group">
    <label class="col-sm-2 control-label">Port passive begin:</label>
    <span class="col-sm-10" > <%= @host.port_passive_begin %> </span>
  </p>

  <p class="form-group">
    <label class="col-sm-2 control-label">Port passive end:</label>
    <span class="col-sm-10" > <%= @host.port_passive_end %> </span>
  </p>
</div>

admin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

admin/app/views/login/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>login</title>
</head>
<body class="login_panel">
<div class="container">
  <% if flash[:error] %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span></button>
       <%= flash[:error] %>
    </div>
  <% end %>
  <div class="form row">
    <form class="form-horizontal col-md-offset-3" action="/login/login" method="post">
      <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
      <h3 class="form-title">文件传输系统</h3>
      <div class="col-md-9">
        <div class="form-group">
          <i class="fa fa-user fa-lg"></i>
          <input class="form-control required" type="text" placeholder="账号" name="name" autofocus="autofocus" maxlength="20"/>
        </div>
        <div class="form-group">
          <i class="fa fa-lock fa-lg"></i>
          <input class="form-control required" type="password" placeholder="密码" name="password" maxlength="8"/>
        </div>
        <div class="form-group col-md-offset-9">
          <button type="submit" class="btn btn-success pull-right" name="submit">登录</button>
        </div>
      </div>
    </form>
  </div>


</div>
</body>
</html>